# Generated by Django 3.2.9 on 2022-02-13 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoiBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_doi_bong', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã đội bóng')),
                ('ten_doi_bong', models.CharField(max_length=50, verbose_name='Tên đội bóng')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo đội bóng')),
            ],
            options={
                'verbose_name': 'Đội bóng',
                'verbose_name_plural': 'Đội bóng',
            },
        ),
        migrations.CreateModel(
            name='TranDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tran_dau', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã trận đấu')),
                ('giai_dau', models.CharField(max_length=50, verbose_name='Giải đấu')),
                ('diem_so', models.CharField(max_length=50, verbose_name='Điểm số')),
                ('dia_diem', models.CharField(max_length=50, verbose_name='Địa điểm')),
                ('thoi_gian', models.DateTimeField(verbose_name='Thời gian')),
                ('trong_tai', models.CharField(default='TBD', max_length=50, verbose_name='Trọng tài')),
                ('ban_thang', tinymce.models.HTMLField(default='TBD', verbose_name='Bàn thắng')),
                ('pham_loi', tinymce.models.HTMLField(default='TBD', verbose_name='Phạm lỗi')),
                ('chien_thuat', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Chiến thuật')),
                ('doi_bong', models.ManyToManyField(blank=True, null=True, related_name='tran_dau', to='daihuu.DoiBong', verbose_name='Đội bóng')),
            ],
            options={
                'verbose_name': 'Trận đấu',
                'verbose_name_plural': 'Trận đấu',
                'ordering': ['-thoi_gian'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_post', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã post')),
                ('tieu_de', models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề')),
                ('noi_dung', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('hinh_dai_dien', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình đại diện')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('the_loai', models.CharField(choices=[('Đại Hữu FC', 'Đại Hữu FC'), ('Bóng đá trong nước', 'Bóng đá trong nước'), ('Bóng đá quốc tế', 'Bóng đá quốc tế')], default='Đại Hữu FC', max_length=100)),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='post_like', to=settings.AUTH_USER_MODEL, verbose_name='Người like')),
                ('tac_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
                'ordering': ['-ngay_dang'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', tinymce.models.HTMLField(verbose_name='Nội dung')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='daihuu.post', verbose_name='Bài viết')),
                ('ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
            },
        ),
        migrations.CreateModel(
            name='CauThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_cau_thu', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã cầu thủ')),
                ('ho', models.CharField(max_length=50, verbose_name='Họ')),
                ('ten', models.CharField(max_length=50, verbose_name='Tên')),
                ('nam_sinh', models.DateField(verbose_name='Năm sinh')),
                ('que_quan', models.CharField(max_length=50, verbose_name='Quê quán')),
                ('chieu_cao', models.CharField(max_length=50, verbose_name='Chiều cao')),
                ('can_nang', models.CharField(max_length=50, verbose_name='Cân nặng')),
                ('so_ao', models.CharField(max_length=50, verbose_name='Số áo')),
                ('vi_tri', models.CharField(max_length=50, verbose_name='Vị trí')),
                ('so_tran', models.CharField(max_length=50, verbose_name='Số trận')),
                ('so_ban_thang', models.CharField(max_length=50, verbose_name='Số bàn thắng')),
                ('so_lan_cuu_thua', models.CharField(max_length=50, verbose_name='Số lần cứu thua')),
                ('tieu_su', models.TextField(verbose_name='Tiểu sử')),
                ('hinh_dai_dien', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình đại diện')),
                ('tinh_trang', models.CharField(max_length=50, verbose_name='Tình trạng')),
                ('doi_hinh', models.CharField(default='Chính thức', max_length=50, verbose_name='Đội hình')),
                ('doi_bong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cau_thu', to='daihuu.doibong', verbose_name='Đội bóng')),
            ],
            options={
                'verbose_name': 'Cầu thủ',
                'verbose_name_plural': 'Cầu thủ',
                'ordering': ['-doi_bong'],
            },
        ),
    ]
