# Generated by Django 3.2.9 on 2022-02-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='the_loai',
            field=models.CharField(choices=[('Đại Hữu FC', 'Đại Hữu FC'), ('Bóng đá trong nước', 'Bóng đá trong nước'), ('Bóng đá quốc tế', 'Bóng đá quốc tế'), ('Y tế', 'Y tế'), ('Giáo dục', 'Giáo dục'), ('Kết nối doanh nghiệp', 'Kết nối doanh nghiệp')], default='Đại Hữu FC', max_length=100, verbose_name='Thể loại'),
        ),
    ]
