# Generated by Django 3.2.9 on 2021-12-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0004_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoiBong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.CreateModel(
            name='DoiHinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50)),
                ('doi_bong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daihuu.doibong')),
            ],
        ),
        migrations.CreateModel(
            name='CauThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho', models.CharField(max_length=50)),
                ('ten', models.CharField(max_length=50)),
                ('nam_sinh', models.DateTimeField()),
                ('que_quan', models.CharField(max_length=50)),
                ('chieu_cao', models.CharField(max_length=50)),
                ('can_nang', models.CharField(max_length=50)),
                ('so_ao', models.CharField(max_length=50)),
                ('vi_tri', models.CharField(max_length=50)),
                ('hinh_dai_dien', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tinh_trang', models.CharField(max_length=50)),
                ('doi_hinh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daihuu.doihinh')),
            ],
        ),
    ]
