# Generated by Django 3.2.9 on 2021-12-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0005_auto_20211207_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doibong',
            old_name='ten',
            new_name='ten_doi_bong',
        ),
        migrations.RemoveField(
            model_name='cauthu',
            name='doi_hinh',
        ),
        migrations.AddField(
            model_name='cauthu',
            name='doi_bong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='daihuu.doibong'),
        ),
        migrations.AddField(
            model_name='cauthu',
            name='ma_cau_thu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doibong',
            name='ma_doi_bong',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ma_post',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='DoiHinh',
        ),
    ]
