# Generated by Django 3.2.9 on 2021-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0006_auto_20211213_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranDau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tran_dau', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('giai_dau', models.CharField(max_length=50)),
                ('diem_so', models.CharField(max_length=50)),
                ('dia_diem', models.CharField(max_length=50)),
                ('thoi_gian', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-ngay_dang']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='hinh_dai_dien',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_on',
            new_name='ngay_dang',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='noi_dung',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='tac_gia',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='tieu_de',
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='ma_cau_thu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='ma_doi_bong',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ma_post',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doibong',
            name='tran_dau',
            field=models.ManyToManyField(blank=True, null=True, to='daihuu.TranDau'),
        ),
    ]
