# Generated by Django 3.2.9 on 2021-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0007_auto_20211213_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doibong',
            name='tran_dau',
        ),
    ]
