# Generated by Django 3.2.9 on 2021-12-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0008_remove_doibong_tran_dau'),
    ]

    operations = [
        migrations.AddField(
            model_name='doibong',
            name='tran_dau',
            field=models.ManyToManyField(blank=True, null=True, to='daihuu.TranDau'),
        ),
    ]
