# Generated by Django 3.2.9 on 2021-12-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0010_auto_20211213_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
