# Generated by Django 3.2.9 on 2022-01-02 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daihuu', '0011_auto_20211229_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='doi_bong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='daihuu.doibong'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='doi_bong',
            field=models.ManyToManyField(blank=True, null=True, related_name='tran_dau', to='daihuu.DoiBong'),
        ),
    ]
