# Generated by Django 3.2.9 on 2022-01-03 07:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0013_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='nam_sinh',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='noi_dung',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
