# Generated by Django 3.2.9 on 2022-01-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0014_auto_20220103_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='nam_sinh',
            field=models.DateTimeField(),
        ),
    ]
