# Generated by Django 3.2.9 on 2022-01-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0015_alter_cauthu_nam_sinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='nam_sinh',
            field=models.DateField(),
        ),
    ]
