# Generated by Django 3.2.9 on 2022-01-03 08:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0016_alter_cauthu_nam_sinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='noi_dung',
            field=ckeditor.fields.RichTextField(blank=True, default='text here', null=True),
        ),
    ]
