# Generated by Django 3.2.9 on 2022-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0017_alter_post_noi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='noi_dung',
            field=models.TextField(),
        ),
    ]
