# Generated by Django 3.2.9 on 2022-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0019_cauthu_so_tran'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauthu',
            name='so_ban_thang',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cauthu',
            name='so_lan_cuu_thua',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cauthu',
            name='tieu_su',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
