# Generated by Django 3.2.9 on 2022-01-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0021_alter_post_hinh_dai_dien'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauthu',
            name='doi_hinh',
            field=models.CharField(default='Chính thức', max_length=50),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
