# Generated by Django 3.2.9 on 2022-01-14 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0022_auto_20220113_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='doi_bong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cau_thu', to='daihuu.doibong'),
        ),
    ]
