# Generated by Django 3.2.9 on 2022-01-14 14:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0024_alter_post_noi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='noi_dung',
            field=tinymce.models.HTMLField(),
        ),
    ]
