# Generated by Django 3.2.9 on 2022-01-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0025_alter_post_noi_dung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tieu_de',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tiêu đề'),
        ),
    ]
