# Generated by Django 3.2.9 on 2022-01-18 22:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0026_alter_post_tieu_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandau',
            name='ban_thang',
            field=tinymce.models.HTMLField(default='Không'),
        ),
        migrations.AddField(
            model_name='trandau',
            name='chien_thuat',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trandau',
            name='pham_loi',
            field=tinymce.models.HTMLField(default='Không'),
        ),
        migrations.AddField(
            model_name='trandau',
            name='trong_tai',
            field=models.CharField(default='Không', max_length=50),
        ),
    ]
