# Generated by Django 3.2.9 on 2022-01-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0027_auto_20220119_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trandau',
            name='trong_tai',
        ),
    ]
