# Generated by Django 3.2.9 on 2022-01-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0028_remove_trandau_trong_tai'),
    ]

    operations = [
        migrations.AddField(
            model_name='trandau',
            name='trong_tai',
            field=models.CharField(default='Không', max_length=50),
        ),
    ]
