# Generated by Django 3.2.9 on 2022-01-24 23:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0030_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='noi_dung',
            field=tinymce.models.HTMLField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ten',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
    ]
