# Generated by Django 3.2.9 on 2022-01-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daihuu', '0032_alter_comment_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ten',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
    ]
