# Generated by Django 3.2.9 on 2022-01-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daihuu', '0034_alter_comment_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cauthu',
            name='can_nang',
            field=models.CharField(max_length=50, verbose_name='Cân nặng'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='chieu_cao',
            field=models.CharField(max_length=50, verbose_name='Chiều cao'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='doi_bong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cau_thu', to='daihuu.doibong', verbose_name='Đội bóng'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='doi_hinh',
            field=models.CharField(default='Chính thức', max_length=50, verbose_name='Đội hình'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='ho',
            field=models.CharField(max_length=50, verbose_name='Họ'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='ma_cau_thu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã cầu thủ'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='nam_sinh',
            field=models.DateField(verbose_name='Năm sinh'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='que_quan',
            field=models.CharField(max_length=50, verbose_name='Quê quán'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='so_ao',
            field=models.CharField(max_length=50, verbose_name='Số áo'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='so_ban_thang',
            field=models.CharField(max_length=50, verbose_name='Số bàn thắng'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='so_lan_cuu_thua',
            field=models.CharField(max_length=50, verbose_name='Số lần cứu thua'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='so_tran',
            field=models.CharField(max_length=50, verbose_name='Số trận'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='ten',
            field=models.CharField(max_length=50, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='tieu_su',
            field=models.TextField(verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='tinh_trang',
            field=models.CharField(max_length=50, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='cauthu',
            name='vi_tri',
            field=models.CharField(max_length=50, verbose_name='Vị trí'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ngay_dang',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='daihuu.post', verbose_name='Bài viết'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận'),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Logo đội bóng'),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='ma_doi_bong',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã đội bóng'),
        ),
        migrations.AlterField(
            model_name='doibong',
            name='ten_doi_bong',
            field=models.CharField(max_length=50, verbose_name='Tên đội bóng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hinh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Hình đại diện'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like', to=settings.AUTH_USER_MODEL, verbose_name='Người like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ma_post',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ngay_dang',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='post',
            name='noi_dung',
            field=tinymce.models.HTMLField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tac_gia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='ban_thang',
            field=tinymce.models.HTMLField(default='TBD', verbose_name='Bàn thắng'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='chien_thuat',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Chiến thuật'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='dia_diem',
            field=models.CharField(max_length=50, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='diem_so',
            field=models.CharField(max_length=50, verbose_name='Điểm số'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='doi_bong',
            field=models.ManyToManyField(blank=True, null=True, related_name='tran_dau', to='daihuu.DoiBong', verbose_name='Đội bóng'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='giai_dau',
            field=models.CharField(max_length=50, verbose_name='Giải đấu'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='ma_tran_dau',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã trận đấu'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='pham_loi',
            field=tinymce.models.HTMLField(default='TBD', verbose_name='Phạm lỗi'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='thoi_gian',
            field=models.DateTimeField(verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='trandau',
            name='trong_tai',
            field=models.CharField(default='TBD', max_length=50, verbose_name='Trọng tài'),
        ),
    ]
